# Generated by Django 3.1 on 2020-08-31 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20200830_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='check_in',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='place',
            name='check_out',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
