# Generated by Django 3.1 on 2020-08-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='end_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='class',
            name='start_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
