# Generated by Django 3.1 on 2020-08-26 22:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='host',
            name='created',
        ),
        migrations.RemoveField(
            model_name='host',
            name='updated',
        ),
        migrations.AddField(
            model_name='host',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='host',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='host',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
    ]
