# Generated by Django 3.1 on 2020-09-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_host_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='is_auth',
            new_name='email_verified',
        ),
    ]
