# Generated by Django 3.1 on 2020-08-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='somm',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
